// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIgx33-srZNJG9RQzYA321zieWwxrTtM',
    appId: '1:358516698133:web:9762f6b0ddbeb1b279321c',
    messagingSenderId: '358516698133',
    projectId: 'save-med-data',
    authDomain: 'save-med-data.firebaseapp.com',
    storageBucket: 'save-med-data.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGWNmKoIm5X-UPT8aWH9L8oIDXLiXZzdE',
    appId: '1:358516698133:android:d3cf41f2e05cb08f79321c',
    messagingSenderId: '358516698133',
    projectId: 'save-med-data',
    storageBucket: 'save-med-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9PdUZTXaR6nwbL-NEKNcAVSWKpLMBmg',
    appId: '1:358516698133:ios:4d5b2429e13a9fd579321c',
    messagingSenderId: '358516698133',
    projectId: 'save-med-data',
    storageBucket: 'save-med-data.appspot.com',
    iosClientId: '358516698133-pf4ve6bd7j4rq8nbrc3n4v9ptufv8qj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
